language: generic
sudo: required
services:
    - docker

# In a real project i would test also the other image which i can simple add here and in the script section to test
before_install:
    - docker build -t kn0rr/multi-docker-reactTest -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true kn0rr/multi-docker-reactTest npm run test

after_success:
    - docker build -t kn0rr/multi-docker-client ./client
    - docker build -t kn0rr/multi-docker-nginx ./nginx
    - docker build -t kn0rr/multi-docker-server ./server
    - docker build -t kn0rr/multi-docker-worker ./worker
# Log in to the docker CLI
    - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin

# Push the images to docker hub
    - docker push  kn0rr/multi-docker-client
    - docker push  kn0rr/multi-docker-nginx
    - docker push  kn0rr/multi-docker-server
    - docker push  kn0rr/multi-docker-worker