apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: ingress-service
    annotations: 
        kubernetes.io/ingress.class: nginx
        # Necessary for regex stuff
        nginx.ingress.kubernetes.io/use-regex: 'true'
        # remove the /api in uri for server
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        # For Https Certificate
        cert-manager.io/cluster-issuer: 'letsencrypt-prod'
        # force user to use https
        nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
    tls:
      - hosts:
         - myholidaydiary.net
         - www.myholidaydiary.net
        secretName: myholidaydiary-net
    rules:
        - host: myholidaydiary.net
          http:
            paths:
                - path: /?(.*)
                  backend:
                    serviceName: client-cluster-ip-service
                    servicePort: 3000
                - path: /api/?(.*)
                  backend:
                    serviceName: server-cluster-ip-service
                    servicePort: 5000
        - host: www.myholidaydiary.net
          http:
            paths:
                - path: /?(.*)
                  backend:
                    serviceName: client-cluster-ip-service
                    servicePort: 3000
                - path: /api/?(.*)
                  backend:
                    serviceName: server-cluster-ip-service
                    servicePort: 5000